### ISSUE TITLE
hi, can you provide a link of the book? please,tkx

### ISSUE THREAD

**Issue by uchenm** [smallnest/Scala-Collections-Cookbook#2]

**Comment by smallnest** [comment]
https://item.m.jd.com/product/11934837.html?price=47.40&fs=1&sid=7b10247239e7c3e1cefd80dd1f881e4f&sf=newM&pos=13&csid=f4f28c49d9a00e32fe4d28e6504d4d13_1527002695220_2_1527002698652&ss_symbol=8&ss_mtest=app_search_none&key=scala
